{
 "title": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Titanic API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Titanic API Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"titanic-api\"}\n"
    }
   ]
  },
  {
   "title": "Titanic API CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"titanic-api\"}[5m])* 100)"
    }
   ]
  },
  {
   "title": "API Network (IN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"titanic-api\", interface=\"eth0\"}[5m])"
    }
   ]
  },
  {
   "title": "API Network (OUT)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"titanic-api\", interface=\"eth0\"}[5m])"
    }
   ]
  },
  { "title": "Titanic DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Titanic DB Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"titanic-db\"}\n"
    }
   ]
  },
  {
   "title": "Titanic DB CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"titanic-db\"}[5m])* 100)"
    }
   ]
  },
  {
   "title": "DB Network (IN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"titanic-db\", interface=\"eth0\"}[5m])"
    }
   ]
  },
  {
   "title": "DB Network (OUT)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"titanic-db\", interface=\"eth0\"}[5m])"
    }
   ]
  }
 ]
}