#Default location is /etc/ansible/hosts 
all:
  vars:
    ansible_user: "ansible" 
    ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}' 
    ansible_become_method: sudo
    ansible_become_pass: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
    ansible_become: yes
debian:
  hosts:
    ubuntu1:
    ubuntu2:
    ubuntu3: 